
/*******************************************************************************
* generated by lcd-image-converter rev.e3ba1ed from 2025-01-31 18:27:03 +0500
* font
* filename: unsaved
* name: FontMono5
* family: Terminal
* size: 12
* style: Normal
* included characters:  !"#$%&'()*+,-./0123456789:;<=>?\x0040ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
* antialiasing: no
* type: monospaced
* encoding: UTF-8
* unicode bom: no
* compacted: no
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 0
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/
#include <stdint.h>
#include "font.h"

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
 typedef struct {
     long int code;
     const tImage *image;
     const int image_left;
     const int image_top;
     const int char_width;
     const int char_height;
     } tChar;
 typedef struct {
     int length;
     const tChar *chars;
     } tFont;
*/

#define FIX_ZERO_LENGTH(length) (length==0?1:length)



#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x20[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x20 = { image_data_FontMono5_0x20,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x21[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙∙∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x00, 0x20, 0x20, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x21 = { image_data_FontMono5_0x21,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x22[FIX_ZERO_LENGTH(12)] = {
    // ∙█∙█∙
    // ∙█∙█∙
    // ∙█∙█∙
    // ∙█∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x50, 0x50, 0x50, 0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x22 = { image_data_FontMono5_0x22,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x23[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙█∙█∙
    // ∙█∙█∙
    // █████
    // ∙█∙█∙
    // ∙█∙█∙
    // █████
    // ∙█∙█∙
    // ∙█∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x50, 0x50, 0xf8, 0x50, 0x50, 0xf8, 0x50, 0x50, 0x00, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x23 = { image_data_FontMono5_0x23,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x24[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙█∙∙∙
    // ∙██∙∙
    // █∙∙█∙
    // █∙∙∙∙
    // ∙█∙∙∙
    // ∙∙█∙∙
    // ∙∙∙█∙
    // █∙∙█∙
    // ∙██∙∙
    // ∙∙█∙∙
    // ∙∙∙∙∙
    0x00, 0x40, 0x60, 0x90, 0x80, 0x40, 0x20, 0x10, 0x90, 0x60, 0x20, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x24 = { image_data_FontMono5_0x24,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x25[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ██∙█∙
    // ██∙█∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // █∙██∙
    // █∙██∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0xd0, 0xd0, 0x20, 0x20, 0x40, 0x40, 0x40, 0xb0, 0xb0, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x25 = { image_data_FontMono5_0x25,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x26[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙█∙∙∙
    // █∙█∙∙
    // █∙█∙∙
    // █∙█∙∙
    // ∙█∙∙∙
    // █∙█∙█
    // █∙∙█∙
    // █∙∙█∙
    // ∙██∙█
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x40, 0xa0, 0xa0, 0xa0, 0x40, 0xa8, 0x90, 0x90, 0x68, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x26 = { image_data_FontMono5_0x26,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x27[FIX_ZERO_LENGTH(12)] = {
    // ∙∙██∙
    // ∙∙██∙
    // ∙∙∙█∙
    // ∙∙█∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x30, 0x30, 0x10, 0x20, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x27 = { image_data_FontMono5_0x27,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x28[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙█∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙∙█∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x20, 0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x20, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x28 = { image_data_FontMono5_0x28,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x29[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙█∙∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙█∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x40, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x40, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x29 = { image_data_FontMono5_0x29,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x2a[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙█∙∙
    // █∙█∙█
    // ∙███∙
    // ∙███∙
    // █∙█∙█
    // ∙∙█∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x20, 0xa8, 0x70, 0x70, 0xa8, 0x20, 0x00, 0x00, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x2a = { image_data_FontMono5_0x2a,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x2b[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // █████
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x00, 0x20, 0x20, 0xf8, 0x20, 0x20, 0x00, 0x00, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x2b = { image_data_FontMono5_0x2b,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x2c[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙██∙∙
    // ∙██∙∙
    // ∙∙█∙∙
    // ∙█∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x60, 0x60, 0x20, 0x40
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x2c = { image_data_FontMono5_0x2c,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x2d[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ████∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0xf0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x2d = { image_data_FontMono5_0x2d,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x2e[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙██∙∙
    // ∙██∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x60, 0x60, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x2e = { image_data_FontMono5_0x2e,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x2f[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙█∙
    // ∙∙∙█∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x10, 0x10, 0x20, 0x20, 0x40, 0x40, 0x40, 0x80, 0x80, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x2f = { image_data_FontMono5_0x2f,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x30[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙███∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ███∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x70, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0xe0, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x30 = { image_data_FontMono5_0x30,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x31[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙█∙∙
    // ∙██∙∙
    // █∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ████∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x20, 0x60, 0xa0, 0x20, 0x20, 0x20, 0x20, 0x20, 0xf0, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x31 = { image_data_FontMono5_0x31,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x32[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙██∙∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙∙∙█∙
    // ∙∙█∙∙
    // ∙█∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // ████∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x60, 0x90, 0x90, 0x10, 0x20, 0x40, 0x80, 0x80, 0xf0, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x32 = { image_data_FontMono5_0x32,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x33[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙██∙∙
    // █∙∙█∙
    // ∙∙∙█∙
    // ∙∙∙█∙
    // ∙██∙∙
    // ∙∙∙█∙
    // ∙∙∙█∙
    // █∙∙█∙
    // ∙██∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x60, 0x90, 0x10, 0x10, 0x60, 0x10, 0x10, 0x90, 0x60, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x33 = { image_data_FontMono5_0x33,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x34[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙█∙
    // ∙∙██∙
    // ∙█∙█∙
    // ∙█∙█∙
    // █∙∙█∙
    // ████∙
    // ∙∙∙█∙
    // ∙∙∙█∙
    // ∙∙∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x10, 0x30, 0x50, 0x50, 0x90, 0xf0, 0x10, 0x10, 0x10, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x34 = { image_data_FontMono5_0x34,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x35[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ████∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // ███∙∙
    // ∙∙∙█∙
    // ∙∙∙█∙
    // █∙∙█∙
    // ∙██∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0xf0, 0x80, 0x80, 0x80, 0xe0, 0x10, 0x10, 0x90, 0x60, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x35 = { image_data_FontMono5_0x35,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x36[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙██∙
    // ∙█∙∙∙
    // █∙∙∙∙
    // ███∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙██∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x30, 0x40, 0x80, 0xe0, 0x90, 0x90, 0x90, 0x90, 0x60, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x36 = { image_data_FontMono5_0x36,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x37[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ████∙
    // ∙∙∙█∙
    // ∙∙∙█∙
    // ∙∙∙█∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0xf0, 0x10, 0x10, 0x10, 0x20, 0x20, 0x40, 0x40, 0x40, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x37 = { image_data_FontMono5_0x37,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x38[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙██∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙██∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙██∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x60, 0x90, 0x90, 0x90, 0x60, 0x90, 0x90, 0x90, 0x60, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x38 = { image_data_FontMono5_0x38,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x39[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙██∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙███∙
    // ∙∙∙█∙
    // ∙∙█∙∙
    // ██∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x60, 0x90, 0x90, 0x90, 0x90, 0x70, 0x10, 0x20, 0xc0, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x39 = { image_data_FontMono5_0x39,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x3a[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙██∙∙
    // ∙██∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙██∙∙
    // ∙██∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x60, 0x60, 0x00, 0x00, 0x60, 0x60, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x3a = { image_data_FontMono5_0x3a,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x3b[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙██∙∙
    // ∙██∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙██∙∙
    // ∙██∙∙
    // ∙∙█∙∙
    // ∙█∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x60, 0x60, 0x00, 0x00, 0x60, 0x60, 0x20, 0x40
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x3b = { image_data_FontMono5_0x3b,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x3c[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙█∙
    // ∙∙█∙∙
    // ∙█∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // ∙█∙∙∙
    // ∙∙█∙∙
    // ∙∙∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x10, 0x20, 0x40, 0x80, 0x80, 0x40, 0x20, 0x10, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x3c = { image_data_FontMono5_0x3c,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x3d[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ████∙
    // ∙∙∙∙∙
    // ████∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0xf0, 0x00, 0xf0, 0x00, 0x00, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x3d = { image_data_FontMono5_0x3d,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x3e[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // █∙∙∙∙
    // ∙█∙∙∙
    // ∙∙█∙∙
    // ∙∙∙█∙
    // ∙∙∙█∙
    // ∙∙█∙∙
    // ∙█∙∙∙
    // █∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x80, 0x40, 0x20, 0x10, 0x10, 0x20, 0x40, 0x80, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x3e = { image_data_FontMono5_0x3e,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x3f[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙██∙∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙∙∙█∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙∙∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x60, 0x90, 0x90, 0x10, 0x20, 0x20, 0x00, 0x20, 0x20, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x3f = { image_data_FontMono5_0x3f,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x40[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙██∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙██∙
    // █∙██∙
    // █∙∙∙∙
    // █∙∙∙∙
    // ∙███∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x60, 0x90, 0x90, 0x90, 0xb0, 0xb0, 0x80, 0x80, 0x70, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x40 = { image_data_FontMono5_0x40,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x41[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙██∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ████∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x60, 0x90, 0x90, 0x90, 0xf0, 0x90, 0x90, 0x90, 0x90, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x41 = { image_data_FontMono5_0x41,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x42[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ███∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ███∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ███∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0xe0, 0x90, 0x90, 0x90, 0xe0, 0x90, 0x90, 0x90, 0xe0, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x42 = { image_data_FontMono5_0x42,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x43[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙██∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙█∙
    // ∙██∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x60, 0x90, 0x90, 0x80, 0x80, 0x80, 0x80, 0x90, 0x60, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x43 = { image_data_FontMono5_0x43,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x44[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ███∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ███∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0xe0, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0xe0, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x44 = { image_data_FontMono5_0x44,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x45[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ████∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // ████∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // ████∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0xf0, 0x80, 0x80, 0x80, 0xf0, 0x80, 0x80, 0x80, 0xf0, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x45 = { image_data_FontMono5_0x45,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x46[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ████∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // ████∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0xf0, 0x80, 0x80, 0x80, 0xf0, 0x80, 0x80, 0x80, 0x80, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x46 = { image_data_FontMono5_0x46,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x47[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙██∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙██∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙██∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x60, 0x90, 0x90, 0x80, 0x80, 0xb0, 0x90, 0x90, 0x60, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x47 = { image_data_FontMono5_0x47,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x48[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ████∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x90, 0x90, 0x90, 0x90, 0xf0, 0x90, 0x90, 0x90, 0x90, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x48 = { image_data_FontMono5_0x48,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x49[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙███∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙███∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x70, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x70, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x49 = { image_data_FontMono5_0x49,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x4a[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙███∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // █∙█∙∙
    // █∙█∙∙
    // ∙█∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x70, 0x20, 0x20, 0x20, 0x20, 0x20, 0xa0, 0xa0, 0x40, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x4a = { image_data_FontMono5_0x4a,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x4b[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙█∙∙
    // █∙█∙∙
    // ██∙∙∙
    // █∙█∙∙
    // █∙█∙∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x90, 0x90, 0xa0, 0xa0, 0xc0, 0xa0, 0xa0, 0x90, 0x90, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x4b = { image_data_FontMono5_0x4b,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x4c[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // ████∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0xf0, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x4c = { image_data_FontMono5_0x4c,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x4d[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // █∙∙█∙
    // █∙∙█∙
    // ████∙
    // ████∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x90, 0x90, 0xf0, 0xf0, 0x90, 0x90, 0x90, 0x90, 0x90, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x4d = { image_data_FontMono5_0x4d,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x4e[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // █∙∙█∙
    // █∙∙█∙
    // ██∙█∙
    // ██∙█∙
    // █∙██∙
    // █∙██∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x90, 0x90, 0xd0, 0xd0, 0xb0, 0xb0, 0x90, 0x90, 0x90, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x4e = { image_data_FontMono5_0x4e,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x4f[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙██∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙██∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x60, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x60, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x4f = { image_data_FontMono5_0x4f,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x50[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ███∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ███∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0xe0, 0x90, 0x90, 0x90, 0xe0, 0x80, 0x80, 0x80, 0x80, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x50 = { image_data_FontMono5_0x50,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x51[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙██∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙██∙∙
    // ∙∙█∙∙
    // ∙∙∙█∙
    0x00, 0x60, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x60, 0x20, 0x10
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x51 = { image_data_FontMono5_0x51,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x52[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ███∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ███∙∙
    // ██∙∙∙
    // █∙█∙∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0xe0, 0x90, 0x90, 0x90, 0xe0, 0xc0, 0xa0, 0x90, 0x90, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x52 = { image_data_FontMono5_0x52,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x53[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙██∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙∙∙
    // ∙██∙∙
    // ∙∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙██∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x60, 0x90, 0x90, 0x80, 0x60, 0x10, 0x90, 0x90, 0x60, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x53 = { image_data_FontMono5_0x53,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x54[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // █████
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0xf8, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x54 = { image_data_FontMono5_0x54,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x55[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙██∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x60, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x55 = { image_data_FontMono5_0x55,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x56[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙█∙█∙
    // ∙█∙█∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x90, 0x90, 0x90, 0x90, 0x90, 0x50, 0x50, 0x20, 0x20, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x56 = { image_data_FontMono5_0x56,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x57[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ████∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0xf0, 0x90, 0x90, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x57 = { image_data_FontMono5_0x57,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x58[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙██∙∙
    // ∙██∙∙
    // ∙██∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x90, 0x90, 0x90, 0x60, 0x60, 0x60, 0x90, 0x90, 0x90, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x58 = { image_data_FontMono5_0x58,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x59[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // █∙∙∙█
    // █∙∙∙█
    // █∙∙∙█
    // ∙█∙█∙
    // ∙█∙█∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x88, 0x88, 0x88, 0x50, 0x50, 0x20, 0x20, 0x20, 0x20, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x59 = { image_data_FontMono5_0x59,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x5a[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ████∙
    // ∙∙∙█∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // ████∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0xf0, 0x10, 0x20, 0x20, 0x40, 0x40, 0x80, 0x80, 0xf0, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x5a = { image_data_FontMono5_0x5a,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x5b[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙██∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙██∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x60, 0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x60, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x5b = { image_data_FontMono5_0x5b,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x5c[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙∙█∙
    // ∙∙∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x80, 0x80, 0x40, 0x40, 0x20, 0x20, 0x20, 0x10, 0x10, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x5c = { image_data_FontMono5_0x5c,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x5d[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙██∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙██∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x60, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x60, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x5d = { image_data_FontMono5_0x5d,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x5e[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙█∙∙
    // ∙█∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x20, 0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x5e = { image_data_FontMono5_0x5e,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x5f[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // █████
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf8
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x5f = { image_data_FontMono5_0x5f,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x60[FIX_ZERO_LENGTH(12)] = {
    // ∙██∙∙
    // ∙██∙∙
    // ∙█∙∙∙
    // ∙∙█∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x60, 0x60, 0x40, 0x20, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x60 = { image_data_FontMono5_0x60,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x61[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙██∙∙
    // ∙∙∙█∙
    // ∙███∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙███∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x60, 0x10, 0x70, 0x90, 0x90, 0x70, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x61 = { image_data_FontMono5_0x61,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x62[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // ███∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ███∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x80, 0x80, 0x80, 0xe0, 0x90, 0x90, 0x90, 0x90, 0xe0, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x62 = { image_data_FontMono5_0x62,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x63[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙███∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // ∙███∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x70, 0x80, 0x80, 0x80, 0x80, 0x70, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x63 = { image_data_FontMono5_0x63,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x64[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙█∙
    // ∙∙∙█∙
    // ∙∙∙█∙
    // ∙███∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙███∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x10, 0x10, 0x10, 0x70, 0x90, 0x90, 0x90, 0x90, 0x70, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x64 = { image_data_FontMono5_0x64,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x65[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙██∙∙
    // █∙∙█∙
    // █∙∙█∙
    // ████∙
    // █∙∙∙∙
    // ∙███∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x60, 0x90, 0x90, 0xf0, 0x80, 0x70, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x65 = { image_data_FontMono5_0x65,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x66[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙█∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ███∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x20, 0x40, 0x40, 0xe0, 0x40, 0x40, 0x40, 0x40, 0x40, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x66 = { image_data_FontMono5_0x66,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x67[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙███∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙███∙
    // ∙∙∙█∙
    // ∙██∙∙
    0x00, 0x00, 0x00, 0x00, 0x70, 0x90, 0x90, 0x90, 0x90, 0x70, 0x10, 0x60
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x67 = { image_data_FontMono5_0x67,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x68[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // ███∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x80, 0x80, 0x80, 0xe0, 0x90, 0x90, 0x90, 0x90, 0x90, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x68 = { image_data_FontMono5_0x68,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x69[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙█∙∙
    // ∙∙∙∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙███∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x20, 0x00, 0x20, 0x20, 0x20, 0x20, 0x20, 0x70, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x69 = { image_data_FontMono5_0x69,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x6a[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙█∙∙
    // ∙∙∙∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // █∙█∙∙
    // ∙█∙∙∙
    0x00, 0x00, 0x20, 0x00, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0xa0, 0x40
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x6a = { image_data_FontMono5_0x6a,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x6b[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙█∙
    // █∙█∙∙
    // ██∙∙∙
    // ██∙∙∙
    // █∙█∙∙
    // █∙∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x80, 0x80, 0x80, 0x90, 0xa0, 0xc0, 0xc0, 0xa0, 0x90, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x6b = { image_data_FontMono5_0x6b,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x6c[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙██∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙███∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x60, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x70, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x6c = { image_data_FontMono5_0x6c,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x6d[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // █∙∙█∙
    // ████∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x90, 0xf0, 0x90, 0x90, 0x90, 0x90, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x6d = { image_data_FontMono5_0x6d,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x6e[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // █∙█∙∙
    // ██∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0xa0, 0xd0, 0x90, 0x90, 0x90, 0x90, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x6e = { image_data_FontMono5_0x6e,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x6f[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙██∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙██∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x60, 0x90, 0x90, 0x90, 0x90, 0x60, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x6f = { image_data_FontMono5_0x6f,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x70[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ███∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ███∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0xe0, 0x90, 0x90, 0x90, 0x90, 0xe0, 0x80, 0x80
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x70 = { image_data_FontMono5_0x70,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x71[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙███∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙███∙
    // ∙∙∙█∙
    // ∙∙∙█∙
    0x00, 0x00, 0x00, 0x00, 0x70, 0x90, 0x90, 0x90, 0x90, 0x70, 0x10, 0x10
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x71 = { image_data_FontMono5_0x71,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x72[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // █∙██∙
    // ∙█∙█∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0xb0, 0x50, 0x40, 0x40, 0x40, 0x40, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x72 = { image_data_FontMono5_0x72,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x73[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙██∙∙
    // █∙∙█∙
    // ∙█∙∙∙
    // ∙∙█∙∙
    // █∙∙█∙
    // ∙██∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x60, 0x90, 0x40, 0x20, 0x90, 0x60, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x73 = { image_data_FontMono5_0x73,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x74[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ███∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙██∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x40, 0x40, 0xe0, 0x40, 0x40, 0x40, 0x40, 0x60, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x74 = { image_data_FontMono5_0x74,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x75[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙███∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x90, 0x90, 0x90, 0x90, 0x90, 0x70, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x75 = { image_data_FontMono5_0x75,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x76[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙█∙█∙
    // ∙█∙█∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x90, 0x90, 0x50, 0x50, 0x20, 0x20, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x76 = { image_data_FontMono5_0x76,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x77[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ████∙
    // █∙∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x90, 0x90, 0x90, 0x90, 0xf0, 0x90, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x77 = { image_data_FontMono5_0x77,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x78[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙██∙∙
    // ∙██∙∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x90, 0x90, 0x60, 0x60, 0x90, 0x90, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x78 = { image_data_FontMono5_0x78,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x79[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙███∙
    // ∙∙∙█∙
    // ███∙∙
    0x00, 0x00, 0x00, 0x00, 0x90, 0x90, 0x90, 0x90, 0x90, 0x70, 0x10, 0xe0
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x79 = { image_data_FontMono5_0x79,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x7a[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ████∙
    // ∙∙∙█∙
    // ∙∙█∙∙
    // ∙█∙∙∙
    // █∙∙∙∙
    // ████∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0xf0, 0x10, 0x20, 0x40, 0x80, 0xf0, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x7a = { image_data_FontMono5_0x7a,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x7b[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙∙█∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // █∙∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙█∙∙∙
    // ∙∙█∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x20, 0x40, 0x40, 0x40, 0x80, 0x40, 0x40, 0x40, 0x20, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x7b = { image_data_FontMono5_0x7b,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x7c[FIX_ZERO_LENGTH(12)] = {
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙∙∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x20, 0x20, 0x20, 0x20, 0x00, 0x20, 0x20, 0x20, 0x20, 0x20, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x7c = { image_data_FontMono5_0x7c,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x7d[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙█∙∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙∙█∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙█∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x40, 0x20, 0x20, 0x20, 0x10, 0x20, 0x20, 0x20, 0x40, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x7d = { image_data_FontMono5_0x7d,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono5_0x7e[FIX_ZERO_LENGTH(12)] = {
    // ∙∙∙∙∙
    // ∙█∙█∙
    // █∙█∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x00, 0x50, 0xa0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
#if 0 == 12
    0xff
#endif
};
static const tImage FontMono5_0x7e = { image_data_FontMono5_0x7e,
    5, 17, 8};
#endif


static const tChar FontMono5_array[] = {

#if (0x0 == 0x0)
  // character: ' '
  {0x20, &FontMono5_0x20, 5, 17, 5, 12 },
#else
  // character: ' ' == ''
  {0x20, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '!'
  {0x21, &FontMono5_0x21, 5, 17, 5, 12 },
#else
  // character: '!' == ''
  {0x21, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '\"'
  {0x22, &FontMono5_0x22, 5, 17, 5, 12 },
#else
  // character: '\"' == ''
  {0x22, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '#'
  {0x23, &FontMono5_0x23, 5, 17, 5, 12 },
#else
  // character: '#' == ''
  {0x23, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '$'
  {0x24, &FontMono5_0x24, 5, 17, 5, 12 },
#else
  // character: '$' == ''
  {0x24, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '%'
  {0x25, &FontMono5_0x25, 5, 17, 5, 12 },
#else
  // character: '%' == ''
  {0x25, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '&'
  {0x26, &FontMono5_0x26, 5, 17, 5, 12 },
#else
  // character: '&' == ''
  {0x26, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '\''
  {0x27, &FontMono5_0x27, 5, 17, 5, 12 },
#else
  // character: '\'' == ''
  {0x27, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '('
  {0x28, &FontMono5_0x28, 5, 17, 5, 12 },
#else
  // character: '(' == ''
  {0x28, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: ')'
  {0x29, &FontMono5_0x29, 5, 17, 5, 12 },
#else
  // character: ')' == ''
  {0x29, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '*'
  {0x2a, &FontMono5_0x2a, 5, 17, 5, 12 },
#else
  // character: '*' == ''
  {0x2a, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '+'
  {0x2b, &FontMono5_0x2b, 5, 17, 5, 12 },
#else
  // character: '+' == ''
  {0x2b, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: ','
  {0x2c, &FontMono5_0x2c, 5, 17, 5, 12 },
#else
  // character: ',' == ''
  {0x2c, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '-'
  {0x2d, &FontMono5_0x2d, 5, 17, 5, 12 },
#else
  // character: '-' == ''
  {0x2d, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '.'
  {0x2e, &FontMono5_0x2e, 5, 17, 5, 12 },
#else
  // character: '.' == ''
  {0x2e, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '/'
  {0x2f, &FontMono5_0x2f, 5, 17, 5, 12 },
#else
  // character: '/' == ''
  {0x2f, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '0'
  {0x30, &FontMono5_0x30, 5, 17, 5, 12 },
#else
  // character: '0' == ''
  {0x30, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '1'
  {0x31, &FontMono5_0x31, 5, 17, 5, 12 },
#else
  // character: '1' == ''
  {0x31, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '2'
  {0x32, &FontMono5_0x32, 5, 17, 5, 12 },
#else
  // character: '2' == ''
  {0x32, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '3'
  {0x33, &FontMono5_0x33, 5, 17, 5, 12 },
#else
  // character: '3' == ''
  {0x33, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '4'
  {0x34, &FontMono5_0x34, 5, 17, 5, 12 },
#else
  // character: '4' == ''
  {0x34, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '5'
  {0x35, &FontMono5_0x35, 5, 17, 5, 12 },
#else
  // character: '5' == ''
  {0x35, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '6'
  {0x36, &FontMono5_0x36, 5, 17, 5, 12 },
#else
  // character: '6' == ''
  {0x36, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '7'
  {0x37, &FontMono5_0x37, 5, 17, 5, 12 },
#else
  // character: '7' == ''
  {0x37, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '8'
  {0x38, &FontMono5_0x38, 5, 17, 5, 12 },
#else
  // character: '8' == ''
  {0x38, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '9'
  {0x39, &FontMono5_0x39, 5, 17, 5, 12 },
#else
  // character: '9' == ''
  {0x39, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: ':'
  {0x3a, &FontMono5_0x3a, 5, 17, 5, 12 },
#else
  // character: ':' == ''
  {0x3a, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: ';'
  {0x3b, &FontMono5_0x3b, 5, 17, 5, 12 },
#else
  // character: ';' == ''
  {0x3b, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '<'
  {0x3c, &FontMono5_0x3c, 5, 17, 5, 12 },
#else
  // character: '<' == ''
  {0x3c, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '='
  {0x3d, &FontMono5_0x3d, 5, 17, 5, 12 },
#else
  // character: '=' == ''
  {0x3d, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '>'
  {0x3e, &FontMono5_0x3e, 5, 17, 5, 12 },
#else
  // character: '>' == ''
  {0x3e, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '?'
  {0x3f, &FontMono5_0x3f, 5, 17, 5, 12 },
#else
  // character: '?' == ''
  {0x3f, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '\@'
  {0x40, &FontMono5_0x40, 5, 17, 5, 12 },
#else
  // character: '\@' == ''
  {0x40, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'A'
  {0x41, &FontMono5_0x41, 5, 17, 5, 12 },
#else
  // character: 'A' == ''
  {0x41, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'B'
  {0x42, &FontMono5_0x42, 5, 17, 5, 12 },
#else
  // character: 'B' == ''
  {0x42, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'C'
  {0x43, &FontMono5_0x43, 5, 17, 5, 12 },
#else
  // character: 'C' == ''
  {0x43, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'D'
  {0x44, &FontMono5_0x44, 5, 17, 5, 12 },
#else
  // character: 'D' == ''
  {0x44, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'E'
  {0x45, &FontMono5_0x45, 5, 17, 5, 12 },
#else
  // character: 'E' == ''
  {0x45, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'F'
  {0x46, &FontMono5_0x46, 5, 17, 5, 12 },
#else
  // character: 'F' == ''
  {0x46, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'G'
  {0x47, &FontMono5_0x47, 5, 17, 5, 12 },
#else
  // character: 'G' == ''
  {0x47, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'H'
  {0x48, &FontMono5_0x48, 5, 17, 5, 12 },
#else
  // character: 'H' == ''
  {0x48, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'I'
  {0x49, &FontMono5_0x49, 5, 17, 5, 12 },
#else
  // character: 'I' == ''
  {0x49, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'J'
  {0x4a, &FontMono5_0x4a, 5, 17, 5, 12 },
#else
  // character: 'J' == ''
  {0x4a, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'K'
  {0x4b, &FontMono5_0x4b, 5, 17, 5, 12 },
#else
  // character: 'K' == ''
  {0x4b, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'L'
  {0x4c, &FontMono5_0x4c, 5, 17, 5, 12 },
#else
  // character: 'L' == ''
  {0x4c, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'M'
  {0x4d, &FontMono5_0x4d, 5, 17, 5, 12 },
#else
  // character: 'M' == ''
  {0x4d, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'N'
  {0x4e, &FontMono5_0x4e, 5, 17, 5, 12 },
#else
  // character: 'N' == ''
  {0x4e, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'O'
  {0x4f, &FontMono5_0x4f, 5, 17, 5, 12 },
#else
  // character: 'O' == ''
  {0x4f, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'P'
  {0x50, &FontMono5_0x50, 5, 17, 5, 12 },
#else
  // character: 'P' == ''
  {0x50, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'Q'
  {0x51, &FontMono5_0x51, 5, 17, 5, 12 },
#else
  // character: 'Q' == ''
  {0x51, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'R'
  {0x52, &FontMono5_0x52, 5, 17, 5, 12 },
#else
  // character: 'R' == ''
  {0x52, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'S'
  {0x53, &FontMono5_0x53, 5, 17, 5, 12 },
#else
  // character: 'S' == ''
  {0x53, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'T'
  {0x54, &FontMono5_0x54, 5, 17, 5, 12 },
#else
  // character: 'T' == ''
  {0x54, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'U'
  {0x55, &FontMono5_0x55, 5, 17, 5, 12 },
#else
  // character: 'U' == ''
  {0x55, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'V'
  {0x56, &FontMono5_0x56, 5, 17, 5, 12 },
#else
  // character: 'V' == ''
  {0x56, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'W'
  {0x57, &FontMono5_0x57, 5, 17, 5, 12 },
#else
  // character: 'W' == ''
  {0x57, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'X'
  {0x58, &FontMono5_0x58, 5, 17, 5, 12 },
#else
  // character: 'X' == ''
  {0x58, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'Y'
  {0x59, &FontMono5_0x59, 5, 17, 5, 12 },
#else
  // character: 'Y' == ''
  {0x59, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'Z'
  {0x5a, &FontMono5_0x5a, 5, 17, 5, 12 },
#else
  // character: 'Z' == ''
  {0x5a, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '['
  {0x5b, &FontMono5_0x5b, 5, 17, 5, 12 },
#else
  // character: '[' == ''
  {0x5b, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '\'
  {0x5c, &FontMono5_0x5c, 5, 17, 5, 12 },
#else
  // character: '\' == ''
  {0x5c, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: ']'
  {0x5d, &FontMono5_0x5d, 5, 17, 5, 12 },
#else
  // character: ']' == ''
  {0x5d, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '^'
  {0x5e, &FontMono5_0x5e, 5, 17, 5, 12 },
#else
  // character: '^' == ''
  {0x5e, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '_'
  {0x5f, &FontMono5_0x5f, 5, 17, 5, 12 },
#else
  // character: '_' == ''
  {0x5f, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '`'
  {0x60, &FontMono5_0x60, 5, 17, 5, 12 },
#else
  // character: '`' == ''
  {0x60, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'a'
  {0x61, &FontMono5_0x61, 5, 17, 5, 12 },
#else
  // character: 'a' == ''
  {0x61, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'b'
  {0x62, &FontMono5_0x62, 5, 17, 5, 12 },
#else
  // character: 'b' == ''
  {0x62, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'c'
  {0x63, &FontMono5_0x63, 5, 17, 5, 12 },
#else
  // character: 'c' == ''
  {0x63, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'd'
  {0x64, &FontMono5_0x64, 5, 17, 5, 12 },
#else
  // character: 'd' == ''
  {0x64, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'e'
  {0x65, &FontMono5_0x65, 5, 17, 5, 12 },
#else
  // character: 'e' == ''
  {0x65, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'f'
  {0x66, &FontMono5_0x66, 5, 17, 5, 12 },
#else
  // character: 'f' == ''
  {0x66, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'g'
  {0x67, &FontMono5_0x67, 5, 17, 5, 12 },
#else
  // character: 'g' == ''
  {0x67, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'h'
  {0x68, &FontMono5_0x68, 5, 17, 5, 12 },
#else
  // character: 'h' == ''
  {0x68, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'i'
  {0x69, &FontMono5_0x69, 5, 17, 5, 12 },
#else
  // character: 'i' == ''
  {0x69, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'j'
  {0x6a, &FontMono5_0x6a, 5, 17, 5, 12 },
#else
  // character: 'j' == ''
  {0x6a, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'k'
  {0x6b, &FontMono5_0x6b, 5, 17, 5, 12 },
#else
  // character: 'k' == ''
  {0x6b, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'l'
  {0x6c, &FontMono5_0x6c, 5, 17, 5, 12 },
#else
  // character: 'l' == ''
  {0x6c, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'm'
  {0x6d, &FontMono5_0x6d, 5, 17, 5, 12 },
#else
  // character: 'm' == ''
  {0x6d, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'n'
  {0x6e, &FontMono5_0x6e, 5, 17, 5, 12 },
#else
  // character: 'n' == ''
  {0x6e, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'o'
  {0x6f, &FontMono5_0x6f, 5, 17, 5, 12 },
#else
  // character: 'o' == ''
  {0x6f, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'p'
  {0x70, &FontMono5_0x70, 5, 17, 5, 12 },
#else
  // character: 'p' == ''
  {0x70, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'q'
  {0x71, &FontMono5_0x71, 5, 17, 5, 12 },
#else
  // character: 'q' == ''
  {0x71, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'r'
  {0x72, &FontMono5_0x72, 5, 17, 5, 12 },
#else
  // character: 'r' == ''
  {0x72, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 's'
  {0x73, &FontMono5_0x73, 5, 17, 5, 12 },
#else
  // character: 's' == ''
  {0x73, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 't'
  {0x74, &FontMono5_0x74, 5, 17, 5, 12 },
#else
  // character: 't' == ''
  {0x74, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'u'
  {0x75, &FontMono5_0x75, 5, 17, 5, 12 },
#else
  // character: 'u' == ''
  {0x75, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'v'
  {0x76, &FontMono5_0x76, 5, 17, 5, 12 },
#else
  // character: 'v' == ''
  {0x76, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'w'
  {0x77, &FontMono5_0x77, 5, 17, 5, 12 },
#else
  // character: 'w' == ''
  {0x77, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'x'
  {0x78, &FontMono5_0x78, 5, 17, 5, 12 },
#else
  // character: 'x' == ''
  {0x78, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'y'
  {0x79, &FontMono5_0x79, 5, 17, 5, 12 },
#else
  // character: 'y' == ''
  {0x79, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: 'z'
  {0x7a, &FontMono5_0x7a, 5, 17, 5, 12 },
#else
  // character: 'z' == ''
  {0x7a, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '{'
  {0x7b, &FontMono5_0x7b, 5, 17, 5, 12 },
#else
  // character: '{' == ''
  {0x7b, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '|'
  {0x7c, &FontMono5_0x7c, 5, 17, 5, 12 },
#else
  // character: '|' == ''
  {0x7c, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '}'
  {0x7d, &FontMono5_0x7d, 5, 17, 5, 12 },
#else
  // character: '}' == ''
  {0x7d, &FontMono5_0x, 5, 17, 5, 12 },
#endif

#if (0x0 == 0x0)
  // character: '~'
  {0x7e, &FontMono5_0x7e, 5, 17, 5, 12 }
#else
  // character: '~' == ''
  {0x7e, &FontMono5_0x, 5, 17, 5, 12 }
#endif

};


const tFont FontMono5 = { 95, FontMono5_array };


#undef FIX_ZERO_LENGTH
