
/*******************************************************************************
* generated by lcd-image-converter rev.e3ba1ed from 2025-01-31 18:27:03 +0500
* font
* filename: unsaved
* name: FontMono8
* family: Cascadia Mono Light
* size: 14
* style: Light
* included characters:  !"#$%&'()*+,-./0123456789:;<=>?\x0040ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
* antialiasing: no
* type: monospaced
* encoding: UTF-8
* unicode bom: no
* compacted: no
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 0
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/
#include <stdint.h>
#include "font.h"

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
 typedef struct {
     long int code;
     const tImage *image;
     const int image_left;
     const int image_top;
     const int char_width;
     const int char_height;
     } tChar;
 typedef struct {
     int length;
     const tChar *chars;
     } tFont;
*/

#define FIX_ZERO_LENGTH(length) (length==0?1:length)



#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x20[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x20 = { image_data_FontMono8_0x20,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x21[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x00, 0x00, 0x18, 0x18, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x21 = { image_data_FontMono8_0x21,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x22[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙█∙█∙∙
    // ∙∙∙█∙█∙∙
    // ∙∙∙█∙█∙∙
    // ∙∙∙█∙█∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x14, 0x14, 0x14, 0x14, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x22 = { image_data_FontMono8_0x22,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x23[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙█∙∙█∙∙
    // ∙∙█∙∙█∙∙
    // ∙██████∙
    // ∙∙█∙∙█∙∙
    // ∙∙█∙∙█∙∙
    // ∙██████∙
    // ∙∙█∙∙█∙∙
    // ∙∙█∙∙█∙∙
    // ∙∙█∙∙█∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x24, 0x24, 0x7e, 0x24, 0x24, 0x7e, 0x24, 0x24, 0x24, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x23 = { image_data_FontMono8_0x23,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x24[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙█∙∙∙
    // ∙∙████∙∙
    // ∙██∙█∙█∙
    // ∙█∙∙█∙∙∙
    // ∙██∙█∙∙∙
    // ∙∙███∙∙∙
    // ∙∙∙∙██∙∙
    // ∙∙∙∙█∙█∙
    // ∙∙∙∙█∙█∙
    // ∙∙∙∙█∙█∙
    // ∙█████∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    0x08, 0x3c, 0x6a, 0x48, 0x68, 0x38, 0x0c, 0x0a, 0x0a, 0x0a, 0x7c, 0x08, 0x08
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x24 = { image_data_FontMono8_0x24,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x25[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙███∙∙∙∙
    // █∙∙∙█∙∙∙
    // █∙∙∙█∙∙∙
    // ∙███∙██∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙█∙███∙
    // ∙█∙∙█∙∙█
    // ∙∙∙∙█∙∙█
    // ∙∙∙∙███∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x70, 0x88, 0x88, 0x76, 0x08, 0x10, 0x2e, 0x49, 0x09, 0x0e, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x25 = { image_data_FontMono8_0x25,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x26[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙████∙∙
    // ∙∙█∙∙∙█∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙∙██∙∙█∙
    // ∙█∙∙█∙█∙
    // █∙∙∙∙██∙
    // ∙█∙∙∙██∙
    // ∙████∙∙█
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x3c, 0x22, 0x40, 0x40, 0x20, 0x32, 0x4a, 0x86, 0x46, 0x79, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x26 = { image_data_FontMono8_0x26,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x27[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x08, 0x08, 0x08, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x27 = { image_data_FontMono8_0x27,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x28[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙███∙
    // ∙∙∙██∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙∙███∙
    // ∙∙∙∙∙∙∙∙
    0x0e, 0x18, 0x10, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x10, 0x18, 0x0e, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x28 = { image_data_FontMono8_0x28,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x29[FIX_ZERO_LENGTH(13)] = {
    // ∙███∙∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙██∙∙
    // ∙∙∙██∙∙∙
    // ∙███∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x70, 0x08, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x0c, 0x18, 0x70, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x29 = { image_data_FontMono8_0x29,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x2a[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙██∙███∙
    // ∙∙∙██∙∙∙
    // ∙∙∙█∙█∙∙
    // ∙∙█∙∙█∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x08, 0x08, 0x6e, 0x18, 0x14, 0x24, 0x00, 0x00, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x2a = { image_data_FontMono8_0x2a,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x2b[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙██████∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x08, 0x08, 0x08, 0x7e, 0x08, 0x08, 0x08, 0x00, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x2b = { image_data_FontMono8_0x2b,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x2c[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0x10, 0x10, 0x10
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x2c = { image_data_FontMono8_0x2c,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x2d[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙██████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x2d = { image_data_FontMono8_0x2d,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x2e[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x18, 0x18, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x2e = { image_data_FontMono8_0x2e,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x2f[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙█
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x01, 0x02, 0x02, 0x04, 0x04, 0x08, 0x08, 0x10, 0x10, 0x20, 0x20, 0x40, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x2f = { image_data_FontMono8_0x2f,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x30[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙████∙∙
    // ∙∙█∙∙██∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙██∙█∙
    // ∙█∙██∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙█∙∙██∙
    // ∙∙████∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x3c, 0x26, 0x42, 0x42, 0x5a, 0x5a, 0x42, 0x42, 0x26, 0x3c, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x30 = { image_data_FontMono8_0x30,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x31[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙███∙∙∙
    // ∙█∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙██████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x38, 0x48, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x7e, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x31 = { image_data_FontMono8_0x31,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x32[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙████∙∙
    // ∙█∙∙∙██∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙██∙∙
    // ∙∙∙██∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙██████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x3c, 0x46, 0x02, 0x02, 0x02, 0x04, 0x0c, 0x18, 0x20, 0x7e, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x32 = { image_data_FontMono8_0x32,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x33[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙████∙∙
    // ∙█∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙∙∙██∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙██∙
    // ∙█████∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x3c, 0x42, 0x02, 0x04, 0x18, 0x06, 0x02, 0x02, 0x06, 0x7c, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x33 = { image_data_FontMono8_0x33,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x34[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙█∙∙█∙∙
    // ∙∙█∙∙█∙∙
    // ∙█∙∙∙█∙∙
    // ∙█∙∙∙█∙∙
    // ∙█∙∙∙█∙∙
    // ∙█∙∙∙█∙∙
    // ∙███████
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x04, 0x24, 0x24, 0x44, 0x44, 0x44, 0x44, 0x7f, 0x04, 0x04, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x34 = { image_data_FontMono8_0x34,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x35[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙█████∙
    // ∙∙█∙∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙∙█████∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙██∙∙∙█∙
    // ∙∙████∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x3e, 0x20, 0x20, 0x20, 0x3e, 0x02, 0x02, 0x42, 0x62, 0x3c, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x35 = { image_data_FontMono8_0x35,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x36[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙███∙
    // ∙∙██∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙██████∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙██∙∙∙█∙
    // ∙∙████∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x0e, 0x30, 0x20, 0x40, 0x7e, 0x42, 0x42, 0x42, 0x62, 0x3c, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x36 = { image_data_FontMono8_0x36,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x37[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙███████
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x7f, 0x42, 0x42, 0x02, 0x04, 0x04, 0x04, 0x08, 0x08, 0x08, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x37 = { image_data_FontMono8_0x37,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x38[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙████∙∙
    // ∙██∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙█∙∙∙█∙
    // ∙∙████∙∙
    // ∙██∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙████∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x3c, 0x62, 0x42, 0x22, 0x3c, 0x62, 0x42, 0x42, 0x42, 0x3c, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x38 = { image_data_FontMono8_0x38,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x39[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙████∙∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙█████∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙██∙
    // ∙∙∙∙██∙∙
    // ∙∙██∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x3c, 0x42, 0x42, 0x42, 0x42, 0x3e, 0x02, 0x06, 0x0c, 0x30, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x39 = { image_data_FontMono8_0x39,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x3a[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x18, 0x18, 0x00, 0x00, 0x00, 0x18, 0x18, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x3a = { image_data_FontMono8_0x3a,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x3b[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x18, 0x18, 0x00, 0x00, 0x00, 0x08, 0x10, 0x10, 0x10
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x3b = { image_data_FontMono8_0x3b,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x3c[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙██∙
    // ∙∙∙██∙∙∙
    // ∙██∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙∙███∙∙∙
    // ∙∙∙∙∙██∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x06, 0x18, 0x60, 0x40, 0x38, 0x06, 0x00, 0x00, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x3c = { image_data_FontMono8_0x3c,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x3d[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙██████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙██████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x7e, 0x00, 0x00, 0x7e, 0x00, 0x00, 0x00, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x3d = { image_data_FontMono8_0x3d,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x3e[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙██∙∙∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙∙∙██∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙██∙∙
    // ∙███∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x60, 0x18, 0x06, 0x02, 0x0c, 0x70, 0x00, 0x00, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x3e = { image_data_FontMono8_0x3e,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x3f[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙████∙∙
    // ∙█∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙██∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x3c, 0x42, 0x02, 0x04, 0x0c, 0x10, 0x10, 0x00, 0x18, 0x18, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x3f = { image_data_FontMono8_0x3f,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x40[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙███∙∙
    // ∙∙█∙∙∙█∙
    // ∙█∙∙███∙
    // ∙█∙█∙∙█∙
    // ∙█∙█∙∙█∙
    // ∙█∙█∙∙█∙
    // ∙█∙█∙∙█∙
    // ∙█∙█∙██∙
    // ∙█∙∙█∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙∙∙███∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x1c, 0x22, 0x4e, 0x52, 0x52, 0x52, 0x52, 0x56, 0x48, 0x20, 0x1c, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x40 = { image_data_FontMono8_0x40,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x41[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙█∙█∙∙
    // ∙∙█∙∙█∙∙
    // ∙∙█∙∙█∙∙
    // ∙∙█∙∙█∙∙
    // ∙██████∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙∙█
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x18, 0x18, 0x14, 0x24, 0x24, 0x24, 0x7e, 0x42, 0x42, 0x41, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x41 = { image_data_FontMono8_0x41,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x42[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙█████∙∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙██∙
    // ∙█████∙∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙∙█
    // ∙█∙∙∙∙∙█
    // ∙█∙∙∙∙█∙
    // ∙██████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x7c, 0x42, 0x42, 0x46, 0x7c, 0x42, 0x41, 0x41, 0x42, 0x7e, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x42 = { image_data_FontMono8_0x42,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x43[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙████∙
    // ∙∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙∙∙████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x1e, 0x20, 0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x20, 0x1e, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x43 = { image_data_FontMono8_0x43,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x44[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙█████∙∙
    // ∙█∙∙∙██∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙∙█
    // ∙█∙∙∙∙∙█
    // ∙█∙∙∙∙∙█
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙██∙
    // ∙█████∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x7c, 0x46, 0x42, 0x42, 0x41, 0x41, 0x41, 0x42, 0x46, 0x7c, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x44 = { image_data_FontMono8_0x44,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x45[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙██████∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█████∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙██████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x7e, 0x40, 0x40, 0x40, 0x7c, 0x40, 0x40, 0x40, 0x40, 0x7e, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x45 = { image_data_FontMono8_0x45,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x46[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙███████
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙██████∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x7f, 0x40, 0x40, 0x40, 0x40, 0x7e, 0x40, 0x40, 0x40, 0x40, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x46 = { image_data_FontMono8_0x46,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x47[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙████∙
    // ∙██∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙███∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙██∙∙∙█∙
    // ∙∙∙████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x1e, 0x60, 0x40, 0x40, 0x40, 0x4e, 0x42, 0x42, 0x62, 0x1e, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x47 = { image_data_FontMono8_0x47,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x48[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙██████∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x42, 0x42, 0x42, 0x42, 0x7e, 0x42, 0x42, 0x42, 0x42, 0x42, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x48 = { image_data_FontMono8_0x48,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x49[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙██████∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙██████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x7e, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x7e, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x49 = { image_data_FontMono8_0x49,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x4a[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙████∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙████∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x1e, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x42, 0x42, 0x3c, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x4a = { image_data_FontMono8_0x4a,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x4b[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙█∙∙
    // ∙█∙∙██∙∙
    // ∙███∙█∙∙
    // ∙█∙∙∙██∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙∙█
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x42, 0x42, 0x42, 0x42, 0x44, 0x4c, 0x74, 0x46, 0x42, 0x41, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x4b = { image_data_FontMono8_0x4b,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x4c[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙██████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x7e, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x4c = { image_data_FontMono8_0x4c,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x4d[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙██∙∙∙█∙
    // ∙██∙∙██∙
    // ∙██∙∙██∙
    // ∙█∙█∙██∙
    // ∙█∙██∙█∙
    // ∙█∙██∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x62, 0x66, 0x66, 0x56, 0x5a, 0x5a, 0x42, 0x42, 0x42, 0x42, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x4d = { image_data_FontMono8_0x4d,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x4e[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙██∙∙∙█∙
    // ∙██∙∙∙█∙
    // ∙█∙█∙∙█∙
    // ∙█∙█∙∙█∙
    // ∙█∙█∙∙█∙
    // ∙█∙∙█∙█∙
    // ∙█∙∙█∙█∙
    // ∙█∙∙∙██∙
    // ∙█∙∙∙██∙
    // ∙█∙∙∙∙█∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x62, 0x62, 0x52, 0x52, 0x52, 0x4a, 0x4a, 0x46, 0x46, 0x42, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x4e = { image_data_FontMono8_0x4e,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x4f[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙████∙∙
    // ∙██∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙∙█
    // ∙█∙∙∙∙∙█
    // ∙█∙∙∙∙∙█
    // ∙█∙∙∙∙█∙
    // ∙██∙∙∙█∙
    // ∙∙████∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x3c, 0x62, 0x42, 0x42, 0x41, 0x41, 0x41, 0x42, 0x62, 0x3c, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x4f = { image_data_FontMono8_0x4f,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x50[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙█████∙∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙∙█
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█████∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x7c, 0x42, 0x42, 0x41, 0x42, 0x42, 0x7c, 0x40, 0x40, 0x40, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x50 = { image_data_FontMono8_0x50,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x51[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙████∙∙
    // ∙██∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙∙█
    // ∙█∙∙∙∙∙█
    // ∙█∙∙∙∙∙█
    // ∙█∙∙∙∙█∙
    // ∙██∙∙∙█∙
    // ∙∙████∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    0x00, 0x3c, 0x62, 0x42, 0x42, 0x41, 0x41, 0x41, 0x42, 0x62, 0x3c, 0x08, 0x08
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x51 = { image_data_FontMono8_0x51,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x52[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙█████∙∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█████∙∙
    // ∙█∙∙∙█∙∙
    // ∙█∙∙∙█∙∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x7c, 0x42, 0x42, 0x42, 0x42, 0x7c, 0x44, 0x44, 0x42, 0x42, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x52 = { image_data_FontMono8_0x52,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x53[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙████∙∙
    // ∙██∙∙∙█∙
    // ∙█∙∙∙∙∙∙
    // ∙██∙∙∙∙∙
    // ∙∙██∙∙∙∙
    // ∙∙∙∙██∙∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙█████∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x3c, 0x62, 0x40, 0x60, 0x30, 0x0c, 0x02, 0x02, 0x02, 0x7c, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x53 = { image_data_FontMono8_0x53,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x54[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙███████
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x7f, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x54 = { image_data_FontMono8_0x54,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x55[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙██∙∙∙█∙
    // ∙∙████∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x62, 0x3c, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x55 = { image_data_FontMono8_0x55,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x56[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙█
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙█∙∙█∙∙
    // ∙∙█∙∙█∙∙
    // ∙∙█∙∙█∙∙
    // ∙∙∙█∙█∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x41, 0x42, 0x42, 0x42, 0x24, 0x24, 0x24, 0x14, 0x18, 0x18, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x56 = { image_data_FontMono8_0x56,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x57[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙█
    // █∙∙∙∙∙∙█
    // ∙█∙██∙∙█
    // ∙█∙██∙∙█
    // ∙█∙██∙█∙
    // ∙█∙██∙█∙
    // ∙█∙██∙█∙
    // ∙█∙█∙██∙
    // ∙██∙∙██∙
    // ∙██∙∙██∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x81, 0x81, 0x59, 0x59, 0x5a, 0x5a, 0x5a, 0x56, 0x66, 0x66, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x57 = { image_data_FontMono8_0x57,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x58[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙█∙∙█∙∙
    // ∙∙∙█∙█∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙█∙∙█∙∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x42, 0x42, 0x24, 0x14, 0x18, 0x18, 0x18, 0x24, 0x42, 0x42, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x58 = { image_data_FontMono8_0x58,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x59[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙█
    // ∙█∙∙∙∙█∙
    // ∙∙█∙∙∙█∙
    // ∙∙█∙∙█∙∙
    // ∙∙∙█∙█∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x41, 0x42, 0x22, 0x24, 0x14, 0x18, 0x08, 0x08, 0x08, 0x08, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x59 = { image_data_FontMono8_0x59,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x5a[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙██████∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙██∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙██████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x7e, 0x02, 0x04, 0x0c, 0x08, 0x10, 0x10, 0x20, 0x40, 0x7e, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x5a = { image_data_FontMono8_0x5a,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x5b[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙████∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙████∙
    0x1e, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x1e
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x5b = { image_data_FontMono8_0x5b,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x5c[FIX_ZERO_LENGTH(13)] = {
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙∙∙
    0x40, 0x40, 0x20, 0x20, 0x10, 0x10, 0x08, 0x08, 0x04, 0x04, 0x04, 0x02, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x5c = { image_data_FontMono8_0x5c,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x5d[FIX_ZERO_LENGTH(13)] = {
    // ∙█████∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙█████∙∙
    0x7c, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x7c
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x5d = { image_data_FontMono8_0x5d,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x5e[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙█∙∙█∙∙
    // ∙∙█∙∙█∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x18, 0x18, 0x24, 0x24, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x5e = { image_data_FontMono8_0x5e,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x5f[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙███████
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7f, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x5f = { image_data_FontMono8_0x5f,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x60[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x10, 0x10, 0x08, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x60 = { image_data_FontMono8_0x60,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x61[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙███∙∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙∙█∙
    // ∙∙█████∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙██∙
    // ∙████∙██
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x38, 0x04, 0x02, 0x3e, 0x42, 0x46, 0x7b, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x61 = { image_data_FontMono8_0x61,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x62[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙███∙∙
    // ∙██∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙██∙
    // ∙████∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x40, 0x40, 0x40, 0x5c, 0x62, 0x42, 0x42, 0x42, 0x46, 0x78, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x62 = { image_data_FontMono8_0x62,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x63[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙█████∙
    // ∙∙█∙∙∙█∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙∙∙████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x3e, 0x22, 0x40, 0x40, 0x40, 0x20, 0x1e, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x63 = { image_data_FontMono8_0x63,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x64[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙███∙█∙
    // ∙█∙∙∙██∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙██∙
    // ∙∙███∙█∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x02, 0x02, 0x02, 0x3a, 0x46, 0x42, 0x42, 0x42, 0x46, 0x3a, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x64 = { image_data_FontMono8_0x64,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x65[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙████∙∙
    // ∙██∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙██████∙
    // ∙█∙∙∙∙∙∙
    // ∙██∙∙∙∙∙
    // ∙∙∙████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x3c, 0x62, 0x42, 0x7e, 0x40, 0x60, 0x1e, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x65 = { image_data_FontMono8_0x65,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x66[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙████
    // ∙∙∙██∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙██████∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x0f, 0x18, 0x10, 0x10, 0x10, 0x7e, 0x10, 0x10, 0x10, 0x10, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x66 = { image_data_FontMono8_0x66,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x67[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙███∙█∙
    // ∙█∙∙∙██∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙██∙
    // ∙∙███∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙∙
    0x00, 0x00, 0x00, 0x00, 0x3a, 0x46, 0x42, 0x42, 0x42, 0x46, 0x3a, 0x02, 0x04
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x67 = { image_data_FontMono8_0x67,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x68[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙███∙∙
    // ∙██∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x40, 0x40, 0x40, 0x5c, 0x62, 0x42, 0x42, 0x42, 0x42, 0x42, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x68 = { image_data_FontMono8_0x68,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x69[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙███∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙██████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x08, 0x08, 0x00, 0x00, 0x38, 0x08, 0x08, 0x08, 0x08, 0x08, 0x7e, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x69 = { image_data_FontMono8_0x69,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x6a[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙████∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙█∙∙∙
    0x04, 0x04, 0x00, 0x00, 0x3c, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x08
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x6a = { image_data_FontMono8_0x6a,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x6b[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙█∙∙
    // ∙█████∙∙
    // ∙█∙∙∙█∙∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x40, 0x40, 0x40, 0x42, 0x42, 0x44, 0x7c, 0x44, 0x42, 0x42, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x6b = { image_data_FontMono8_0x6b,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x6c[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙███∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙∙███∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x70, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x0e, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x6c = { image_data_FontMono8_0x6c,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x6d[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙███∙██∙
    // ∙█∙∙█∙█∙
    // ∙█∙∙█∙█∙
    // ∙█∙∙█∙█∙
    // ∙█∙∙█∙█∙
    // ∙█∙∙█∙█∙
    // ∙█∙∙█∙█∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x76, 0x4a, 0x4a, 0x4a, 0x4a, 0x4a, 0x4a, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x6d = { image_data_FontMono8_0x6d,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x6e[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙█∙███∙∙
    // ∙██∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x5c, 0x62, 0x42, 0x42, 0x42, 0x42, 0x42, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x6e = { image_data_FontMono8_0x6e,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x6f[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙████∙∙
    // ∙██∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙██∙∙∙█∙
    // ∙∙████∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x3c, 0x62, 0x42, 0x42, 0x42, 0x62, 0x3c, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x6f = { image_data_FontMono8_0x6f,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x70[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙█∙███∙∙
    // ∙██∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙██∙∙∙█∙
    // ∙█∙███∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x5c, 0x62, 0x42, 0x42, 0x42, 0x62, 0x5c, 0x40, 0x40
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x70 = { image_data_FontMono8_0x70,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x71[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙███∙█∙
    // ∙█∙∙∙██∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙█████∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    0x00, 0x00, 0x00, 0x00, 0x3a, 0x46, 0x42, 0x42, 0x42, 0x42, 0x3e, 0x02, 0x02
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x71 = { image_data_FontMono8_0x71,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x72[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙██∙███∙
    // ∙∙██∙∙∙█
    // ∙∙██∙∙∙█
    // ∙∙█∙∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙████∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x6e, 0x31, 0x31, 0x20, 0x20, 0x20, 0x78, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x72 = { image_data_FontMono8_0x72,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x73[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙█████∙
    // ∙█∙∙∙∙∙∙
    // ∙██∙∙∙∙∙
    // ∙∙∙███∙∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙█████∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x3e, 0x40, 0x60, 0x1c, 0x02, 0x02, 0x7c, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x73 = { image_data_FontMono8_0x73,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x74[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙██████∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x10, 0x10, 0x7e, 0x10, 0x10, 0x10, 0x10, 0x10, 0x1e, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x74 = { image_data_FontMono8_0x74,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x75[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙██∙
    // ∙∙███∙██
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x42, 0x42, 0x42, 0x42, 0x42, 0x46, 0x3b, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x75 = { image_data_FontMono8_0x75,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x76[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙█∙∙∙█∙
    // ∙∙█∙∙█∙∙
    // ∙∙█∙∙█∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x42, 0x42, 0x22, 0x24, 0x24, 0x18, 0x18, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x76 = { image_data_FontMono8_0x76,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x77[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙██∙∙█
    // ∙█∙██∙█∙
    // ∙█∙██∙█∙
    // ∙█∙██∙█∙
    // ∙█∙█∙██∙
    // ∙██∙∙██∙
    // ∙∙█∙∙█∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x19, 0x5a, 0x5a, 0x5a, 0x56, 0x66, 0x24, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x77 = { image_data_FontMono8_0x77,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x78[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙█∙∙∙∙█∙
    // ∙∙█∙∙█∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙█∙∙█∙∙
    // ∙█∙∙∙∙█∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x42, 0x24, 0x18, 0x08, 0x18, 0x24, 0x42, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x78 = { image_data_FontMono8_0x78,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x79[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙█∙∙∙█∙
    // ∙∙█∙∙█∙∙
    // ∙∙█∙∙█∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙██∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x42, 0x42, 0x22, 0x24, 0x24, 0x18, 0x18, 0x10, 0x30
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x79 = { image_data_FontMono8_0x79,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x7a[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙██████∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙██∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙██████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x7e, 0x04, 0x0c, 0x18, 0x10, 0x20, 0x7e, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x7a = { image_data_FontMono8_0x7a,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x7b[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙███∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙██∙∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙███∙
    0x0e, 0x08, 0x10, 0x08, 0x08, 0x08, 0x30, 0x08, 0x08, 0x08, 0x10, 0x08, 0x0e
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x7b = { image_data_FontMono8_0x7b,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x7c[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x7c = { image_data_FontMono8_0x7c,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x7d[FIX_ZERO_LENGTH(13)] = {
    // ∙∙██∙∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙██∙∙∙∙
    0x30, 0x08, 0x08, 0x10, 0x10, 0x18, 0x04, 0x18, 0x10, 0x08, 0x08, 0x18, 0x30
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x7d = { image_data_FontMono8_0x7d,
    8, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_FontMono8_0x7e[FIX_ZERO_LENGTH(13)] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙███∙∙∙∙
    // ∙█∙∙█∙█∙
    // ∙█∙∙∙██∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x70, 0x4a, 0x46, 0x00, 0x00, 0x00, 0x00, 0x00
#if 0 == 13
    0xff
#endif
};
static const tImage FontMono8_0x7e = { image_data_FontMono8_0x7e,
    8, 13, 8};
#endif


static const tChar FontMono8_array[] = {

#if (0x0 == 0x0)
  // character: ' '
  {0x20, &FontMono8_0x20, 8, 13, 8, 13 },
#else
  // character: ' ' == ''
  {0x20, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '!'
  {0x21, &FontMono8_0x21, 8, 13, 8, 13 },
#else
  // character: '!' == ''
  {0x21, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '\"'
  {0x22, &FontMono8_0x22, 8, 13, 8, 13 },
#else
  // character: '\"' == ''
  {0x22, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '#'
  {0x23, &FontMono8_0x23, 8, 13, 8, 13 },
#else
  // character: '#' == ''
  {0x23, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '$'
  {0x24, &FontMono8_0x24, 8, 13, 8, 13 },
#else
  // character: '$' == ''
  {0x24, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '%'
  {0x25, &FontMono8_0x25, 8, 13, 8, 13 },
#else
  // character: '%' == ''
  {0x25, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '&'
  {0x26, &FontMono8_0x26, 8, 13, 8, 13 },
#else
  // character: '&' == ''
  {0x26, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '\''
  {0x27, &FontMono8_0x27, 8, 13, 8, 13 },
#else
  // character: '\'' == ''
  {0x27, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '('
  {0x28, &FontMono8_0x28, 8, 13, 8, 13 },
#else
  // character: '(' == ''
  {0x28, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: ')'
  {0x29, &FontMono8_0x29, 8, 13, 8, 13 },
#else
  // character: ')' == ''
  {0x29, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '*'
  {0x2a, &FontMono8_0x2a, 8, 13, 8, 13 },
#else
  // character: '*' == ''
  {0x2a, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '+'
  {0x2b, &FontMono8_0x2b, 8, 13, 8, 13 },
#else
  // character: '+' == ''
  {0x2b, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: ','
  {0x2c, &FontMono8_0x2c, 8, 13, 8, 13 },
#else
  // character: ',' == ''
  {0x2c, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '-'
  {0x2d, &FontMono8_0x2d, 8, 13, 8, 13 },
#else
  // character: '-' == ''
  {0x2d, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '.'
  {0x2e, &FontMono8_0x2e, 8, 13, 8, 13 },
#else
  // character: '.' == ''
  {0x2e, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '/'
  {0x2f, &FontMono8_0x2f, 8, 13, 8, 13 },
#else
  // character: '/' == ''
  {0x2f, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '0'
  {0x30, &FontMono8_0x30, 8, 13, 8, 13 },
#else
  // character: '0' == ''
  {0x30, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '1'
  {0x31, &FontMono8_0x31, 8, 13, 8, 13 },
#else
  // character: '1' == ''
  {0x31, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '2'
  {0x32, &FontMono8_0x32, 8, 13, 8, 13 },
#else
  // character: '2' == ''
  {0x32, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '3'
  {0x33, &FontMono8_0x33, 8, 13, 8, 13 },
#else
  // character: '3' == ''
  {0x33, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '4'
  {0x34, &FontMono8_0x34, 8, 13, 8, 13 },
#else
  // character: '4' == ''
  {0x34, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '5'
  {0x35, &FontMono8_0x35, 8, 13, 8, 13 },
#else
  // character: '5' == ''
  {0x35, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '6'
  {0x36, &FontMono8_0x36, 8, 13, 8, 13 },
#else
  // character: '6' == ''
  {0x36, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '7'
  {0x37, &FontMono8_0x37, 8, 13, 8, 13 },
#else
  // character: '7' == ''
  {0x37, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '8'
  {0x38, &FontMono8_0x38, 8, 13, 8, 13 },
#else
  // character: '8' == ''
  {0x38, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '9'
  {0x39, &FontMono8_0x39, 8, 13, 8, 13 },
#else
  // character: '9' == ''
  {0x39, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: ':'
  {0x3a, &FontMono8_0x3a, 8, 13, 8, 13 },
#else
  // character: ':' == ''
  {0x3a, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: ';'
  {0x3b, &FontMono8_0x3b, 8, 13, 8, 13 },
#else
  // character: ';' == ''
  {0x3b, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '<'
  {0x3c, &FontMono8_0x3c, 8, 13, 8, 13 },
#else
  // character: '<' == ''
  {0x3c, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '='
  {0x3d, &FontMono8_0x3d, 8, 13, 8, 13 },
#else
  // character: '=' == ''
  {0x3d, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '>'
  {0x3e, &FontMono8_0x3e, 8, 13, 8, 13 },
#else
  // character: '>' == ''
  {0x3e, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '?'
  {0x3f, &FontMono8_0x3f, 8, 13, 8, 13 },
#else
  // character: '?' == ''
  {0x3f, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '\@'
  {0x40, &FontMono8_0x40, 8, 13, 8, 13 },
#else
  // character: '\@' == ''
  {0x40, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'A'
  {0x41, &FontMono8_0x41, 8, 13, 8, 13 },
#else
  // character: 'A' == ''
  {0x41, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'B'
  {0x42, &FontMono8_0x42, 8, 13, 8, 13 },
#else
  // character: 'B' == ''
  {0x42, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'C'
  {0x43, &FontMono8_0x43, 8, 13, 8, 13 },
#else
  // character: 'C' == ''
  {0x43, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'D'
  {0x44, &FontMono8_0x44, 8, 13, 8, 13 },
#else
  // character: 'D' == ''
  {0x44, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'E'
  {0x45, &FontMono8_0x45, 8, 13, 8, 13 },
#else
  // character: 'E' == ''
  {0x45, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'F'
  {0x46, &FontMono8_0x46, 8, 13, 8, 13 },
#else
  // character: 'F' == ''
  {0x46, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'G'
  {0x47, &FontMono8_0x47, 8, 13, 8, 13 },
#else
  // character: 'G' == ''
  {0x47, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'H'
  {0x48, &FontMono8_0x48, 8, 13, 8, 13 },
#else
  // character: 'H' == ''
  {0x48, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'I'
  {0x49, &FontMono8_0x49, 8, 13, 8, 13 },
#else
  // character: 'I' == ''
  {0x49, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'J'
  {0x4a, &FontMono8_0x4a, 8, 13, 8, 13 },
#else
  // character: 'J' == ''
  {0x4a, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'K'
  {0x4b, &FontMono8_0x4b, 8, 13, 8, 13 },
#else
  // character: 'K' == ''
  {0x4b, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'L'
  {0x4c, &FontMono8_0x4c, 8, 13, 8, 13 },
#else
  // character: 'L' == ''
  {0x4c, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'M'
  {0x4d, &FontMono8_0x4d, 8, 13, 8, 13 },
#else
  // character: 'M' == ''
  {0x4d, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'N'
  {0x4e, &FontMono8_0x4e, 8, 13, 8, 13 },
#else
  // character: 'N' == ''
  {0x4e, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'O'
  {0x4f, &FontMono8_0x4f, 8, 13, 8, 13 },
#else
  // character: 'O' == ''
  {0x4f, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'P'
  {0x50, &FontMono8_0x50, 8, 13, 8, 13 },
#else
  // character: 'P' == ''
  {0x50, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'Q'
  {0x51, &FontMono8_0x51, 8, 13, 8, 13 },
#else
  // character: 'Q' == ''
  {0x51, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'R'
  {0x52, &FontMono8_0x52, 8, 13, 8, 13 },
#else
  // character: 'R' == ''
  {0x52, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'S'
  {0x53, &FontMono8_0x53, 8, 13, 8, 13 },
#else
  // character: 'S' == ''
  {0x53, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'T'
  {0x54, &FontMono8_0x54, 8, 13, 8, 13 },
#else
  // character: 'T' == ''
  {0x54, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'U'
  {0x55, &FontMono8_0x55, 8, 13, 8, 13 },
#else
  // character: 'U' == ''
  {0x55, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'V'
  {0x56, &FontMono8_0x56, 8, 13, 8, 13 },
#else
  // character: 'V' == ''
  {0x56, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'W'
  {0x57, &FontMono8_0x57, 8, 13, 8, 13 },
#else
  // character: 'W' == ''
  {0x57, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'X'
  {0x58, &FontMono8_0x58, 8, 13, 8, 13 },
#else
  // character: 'X' == ''
  {0x58, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'Y'
  {0x59, &FontMono8_0x59, 8, 13, 8, 13 },
#else
  // character: 'Y' == ''
  {0x59, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'Z'
  {0x5a, &FontMono8_0x5a, 8, 13, 8, 13 },
#else
  // character: 'Z' == ''
  {0x5a, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '['
  {0x5b, &FontMono8_0x5b, 8, 13, 8, 13 },
#else
  // character: '[' == ''
  {0x5b, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '\'
  {0x5c, &FontMono8_0x5c, 8, 13, 8, 13 },
#else
  // character: '\' == ''
  {0x5c, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: ']'
  {0x5d, &FontMono8_0x5d, 8, 13, 8, 13 },
#else
  // character: ']' == ''
  {0x5d, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '^'
  {0x5e, &FontMono8_0x5e, 8, 13, 8, 13 },
#else
  // character: '^' == ''
  {0x5e, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '_'
  {0x5f, &FontMono8_0x5f, 8, 13, 8, 13 },
#else
  // character: '_' == ''
  {0x5f, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '`'
  {0x60, &FontMono8_0x60, 8, 13, 8, 13 },
#else
  // character: '`' == ''
  {0x60, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'a'
  {0x61, &FontMono8_0x61, 8, 13, 8, 13 },
#else
  // character: 'a' == ''
  {0x61, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'b'
  {0x62, &FontMono8_0x62, 8, 13, 8, 13 },
#else
  // character: 'b' == ''
  {0x62, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'c'
  {0x63, &FontMono8_0x63, 8, 13, 8, 13 },
#else
  // character: 'c' == ''
  {0x63, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'd'
  {0x64, &FontMono8_0x64, 8, 13, 8, 13 },
#else
  // character: 'd' == ''
  {0x64, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'e'
  {0x65, &FontMono8_0x65, 8, 13, 8, 13 },
#else
  // character: 'e' == ''
  {0x65, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'f'
  {0x66, &FontMono8_0x66, 8, 13, 8, 13 },
#else
  // character: 'f' == ''
  {0x66, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'g'
  {0x67, &FontMono8_0x67, 8, 13, 8, 13 },
#else
  // character: 'g' == ''
  {0x67, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'h'
  {0x68, &FontMono8_0x68, 8, 13, 8, 13 },
#else
  // character: 'h' == ''
  {0x68, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'i'
  {0x69, &FontMono8_0x69, 8, 13, 8, 13 },
#else
  // character: 'i' == ''
  {0x69, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'j'
  {0x6a, &FontMono8_0x6a, 8, 13, 8, 13 },
#else
  // character: 'j' == ''
  {0x6a, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'k'
  {0x6b, &FontMono8_0x6b, 8, 13, 8, 13 },
#else
  // character: 'k' == ''
  {0x6b, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'l'
  {0x6c, &FontMono8_0x6c, 8, 13, 8, 13 },
#else
  // character: 'l' == ''
  {0x6c, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'm'
  {0x6d, &FontMono8_0x6d, 8, 13, 8, 13 },
#else
  // character: 'm' == ''
  {0x6d, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'n'
  {0x6e, &FontMono8_0x6e, 8, 13, 8, 13 },
#else
  // character: 'n' == ''
  {0x6e, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'o'
  {0x6f, &FontMono8_0x6f, 8, 13, 8, 13 },
#else
  // character: 'o' == ''
  {0x6f, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'p'
  {0x70, &FontMono8_0x70, 8, 13, 8, 13 },
#else
  // character: 'p' == ''
  {0x70, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'q'
  {0x71, &FontMono8_0x71, 8, 13, 8, 13 },
#else
  // character: 'q' == ''
  {0x71, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'r'
  {0x72, &FontMono8_0x72, 8, 13, 8, 13 },
#else
  // character: 'r' == ''
  {0x72, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 's'
  {0x73, &FontMono8_0x73, 8, 13, 8, 13 },
#else
  // character: 's' == ''
  {0x73, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 't'
  {0x74, &FontMono8_0x74, 8, 13, 8, 13 },
#else
  // character: 't' == ''
  {0x74, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'u'
  {0x75, &FontMono8_0x75, 8, 13, 8, 13 },
#else
  // character: 'u' == ''
  {0x75, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'v'
  {0x76, &FontMono8_0x76, 8, 13, 8, 13 },
#else
  // character: 'v' == ''
  {0x76, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'w'
  {0x77, &FontMono8_0x77, 8, 13, 8, 13 },
#else
  // character: 'w' == ''
  {0x77, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'x'
  {0x78, &FontMono8_0x78, 8, 13, 8, 13 },
#else
  // character: 'x' == ''
  {0x78, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'y'
  {0x79, &FontMono8_0x79, 8, 13, 8, 13 },
#else
  // character: 'y' == ''
  {0x79, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: 'z'
  {0x7a, &FontMono8_0x7a, 8, 13, 8, 13 },
#else
  // character: 'z' == ''
  {0x7a, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '{'
  {0x7b, &FontMono8_0x7b, 8, 13, 8, 13 },
#else
  // character: '{' == ''
  {0x7b, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '|'
  {0x7c, &FontMono8_0x7c, 8, 13, 8, 13 },
#else
  // character: '|' == ''
  {0x7c, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '}'
  {0x7d, &FontMono8_0x7d, 8, 13, 8, 13 },
#else
  // character: '}' == ''
  {0x7d, &FontMono8_0x, 8, 13, 8, 13 },
#endif

#if (0x0 == 0x0)
  // character: '~'
  {0x7e, &FontMono8_0x7e, 8, 13, 8, 13 }
#else
  // character: '~' == ''
  {0x7e, &FontMono8_0x, 8, 13, 8, 13 }
#endif

};


const tFont FontMono8 = { 95, FontMono8_array };


#undef FIX_ZERO_LENGTH
